name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Run linter
      run: bundle exec standardrb

  aardvark-fixture-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install json schema validator
      run: gem install json_schemer
    - name: Run json_schemer against aarkvark fixtures
      run: find spec/fixtures/solr_documents -type f -name "*.json" | xargs json_schemer schema/geoblacklight-schema-aardvark.json

  pr-artifacts:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_VERSION: 7.1.3
    - name: Setup Yarn
      run: exec "yarnpkg"
    - name: Build
      run: BRANCH=${{ github.head_ref || github.ref_name }} rails new gbl-app -m template.rb
    - name: Copy Dockerfile
      run: cp lib/generators/geoblacklight/templates/Dockerfile gbl-app/.
    - name: Copy compose.yml
      run: cp lib/generators/geoblacklight/templates/compose.yml gbl-app/.
    - name: Cleanup
      run: rm -rf gbl-app/node_modules gbl-app/Gemfile.lock gbl-app/yarn.lock gbl-app/tmp
    - name: Zip files
      run: zip -r build.zip gbl-app
    - name: Pull request artifacts
      uses: gavv/pull-request-artifacts@v2
      with:
        commit: ${{ github.event.pull_request.head.sha }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        artifacts-branch: build-repository
        artifacts: build.zip

  build-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_VERSION: 7.1.3
    - name: Setup Yarn
      run: exec "yarnpkg"
    - name: Build
      run: BRANCH=${{ github.head_ref || github.ref_name }} rails new gbl-app -m template.rb
    - name: Copy Dockerfile
      run: cp lib/generators/geoblacklight/templates/Dockerfile gbl-app/.
    - name: Copy compose.yml
      run: cp lib/generators/geoblacklight/templates/compose.yml gbl-app/.
    - name: Cleanup
      run: rm -rf gbl-app/node_modules gbl-app/Gemfile.lock gbl-app/yarn.lock gbl-app/tmp
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: build
        path: gbl-app/
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ['3.3']
        rails_version: [7.1.3]

    name: test ruby ${{ matrix.ruby_version }} / rails ${{ matrix.rails_version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Create Solr container
      run: docker run -d -p 8983:8983 geoblacklight/solr:8.9-v1.0.0 server/scripts/ci-start.sh
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Setup Yarn
      run: exec "yarnpkg"
    - name: Load config into solr
      run: |
          cd solr/conf
          zip -1 -r solr_config.zip ./*
          curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://solr:SolrRocks@127.0.0.1:8983/solr/admin/configs?action=UPLOAD&name=blacklight"
          curl -H 'Content-type: application/json' http://solr:SolrRocks@127.0.0.1:8983/api/collections/  -d '{create: {name: blacklight-core, config: blacklight, numShards: 1}}'
    - name: Run tests
      run: bundle exec rake ci
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test --skip-webpack-install --skip-javascript'
        SOLR_URL: http://solr:SolrRocks@localhost:8983/solr/blacklight-core
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: coverage
        path: coverage/
